/** Declaration file generated by dts-gen */

export function render(data: string): string;

export class Token {
    //解析类型
    code: string
    //解析数据
    map: any
    Tokens: Token[]
    StrList: string[]

    txt:string

}


export class Tokens {
    line: number;
    tokens: Token[]
}

export class PlugTrans {
    code:string
    inLineType: string[]

    parser(lines: string[]): Tokens

    render(token: Token):Token

}

export class Lram {
    public use(p: PlugTrans)
    public render(p: string): string
}
